es = {
	"Franklin D. Roosevelt": "Franklin D. Roosevelt",
	"Franklin Roosevelt": "Franklin Roosevelt",
	"Donald Trump": "Donald Trump",
	"NATO": "OTAN",
	"Barack Obama": "Barack Obama",
	"Obama": "Obama", 
	"Pearl Harbor": "Pearl Harbor",
	"Nazi": "Nazi",
	"Germany": "Alemania",
	"Adolf": "Adolf",
	"Japan": "Japon",
	"Holocaust": "Holocausto",
	"World War II": "Segunda Guerra Mundial",
	"Allies": "Aliados",
	"France": "Francia",
	"Poland": "Polonia",
	"China": "República de China",
	"Final Solution", "Solución Final",
	"genocide": "genocidio",
	"Democratic": "Demócrata",
	"United States": "Estados Unidos",
	"Afghanistan": "Afganistán",
	"Obama": "Obama",
	"LGBT": "LGBT",
	"Russia": "Rusia",
}